const CONST_MAP = {
  INIT_TRIP: "JPY_TRIP/INIT_TRIP",
  DROP_TRIP: "JPY_TRIP/DROP_TRIP",
  SET_UNIT: "JPY_TRIP/SET_UNIT",
  SET_TITLE: "JPY_TRIP/SET_TITLE",
  CONFIRM: "JPY_TRIP/CONFIRM"
};

export default CONST_MAP;
